version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile.mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: {root_password}
      MYSQL_DATABASE: {database_name}
      MYSQL_USER: {user_name}
      MYSQL_PASSWORD: {user_password}
